export const SAVE_USERNAME = 'SAVE_USERNAME'
export const SAVE_ADMIN_STATUS = 'SAVE_ADMIN_STATUS'
export const POST_USER_PERMISSON_ERROR = 'POST_USER_PERMISSON_ERROR'
export const CLEAR_USER_PERMISSION_ERROR = 'CLEAR_USER_PERMISSION_ERROR'

export const FETCHING_STARTUP_DATA = 'FETCHING_STARTUP_DATA'
export const RETRIEVED_STARTUP_DATA = 'RETRIEVED_STARTUP_DATA'
